version: "3.8"
services:
  base_image:
    build:
      context: .
      dockerfile: ./devops/base/Dockerfile
    container_name: messager_base_image
    command: sleep 1000

  main_app:
    restart: always
    build:
      context: .
      dockerfile: ./devops/messager/Dockerfile
    volumes:
      - ./app:/app
    ports:
      - 80:80
    depends_on:
      - base_image

  postgres:
    restart: always
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

volumes:
  postgres-data: